### DISCUSSION TITLE
请问docker部署不能修改端口号吗？

### DISCUSSION THREAD

**Discussion by FASUZO** [zdz/ServerStatus-Rust#144] [Q&A] [answered]
修改文件源链接：https://github.com/FASUZO/ServerStatus-Rust

部署命令：
```bash
wget --no-check-certificate -qO docker-compose.yml 'https://raw.githubusercontent.com/fasuzo/ServerStatus-Rust/master/docker-compose.yml'
wget --no-check-certificate -qO config.toml 'https://raw.githubusercontent.com/fasuzo/ServerStatus-Rust/master/config.toml'
touch stats.json
docker-compose up -d
```

docker日志：
![image](https://user-images.githubusercontent.com/77849230/216751323-d4c8f21f-9238-48b4-8f72-b5d3e74e3abf.png)

web：
![image](https://user-images.githubusercontent.com/77849230/216751356-b4ddc16a-d4f9-40a5-8205-db7f31816219.png)

端口：
![image](https://user-images.githubusercontent.com/77849230/216751413-65cf4bf8-7c59-412b-b451-ca7a672eb694.png)

**Comment by zdz** [comment, marked as answer]
config.toml 文件的端口 8080 不用改

```yml
version: "3"

services:
  stat_server:
    image: idoge/stat_server:latest
    container_name: stat_server
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.toml:/config.toml
      - ./stats.json:/stats.json
    ports:
      - 10006:8080
      - 10106:9394
```
`10006:8080` 第一个是主机外面要使用的端口，第二个是容器里面端口
